### PR TITLE
Link with a newer version of libreadline

### PR DESCRIPTION
**Pull request by igortg**
Currently binary is linking with libreadline v6, which is somewhat old. Change build number so it'll use a newer libreadline

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by igortg** [comment]
@conda-forge-admin please re-render

**Comment by igortg** [comment]
@conda-forge-admin, please rerender

**Comment by xhochy** [comment]
@igortg This is already built against readline 8, so this PR should be unnecessary. There is not change in the relevant section of e.g. `.ci_support/osx_.yaml `.

**Comment by igortg** [comment]
Just found it. Sorry

**Pull request closed without merging**
