### PR TITLE
Bump to 1.3.9

### PR DESCRIPTION
**Pull request by epruesse**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by epruesse** [comment]
https://github.com/conda-forge/freetds-feedstock

**Comment by epruesse** [comment]
@conda-forge-admin, please rerender

**Comment by epruesse** [comment]
@mariusvniekerk I'm seeing "make: command not found" in the `./configure` call here. Is there something off with the docker container?

**Comment by epruesse** [comment]
license file missing

**Comment by mariusvniekerk** [comment]
Make hasn't been included in the base container for at least 2-3 years now. You can add it as a build dependemcy

**Pull request closed without merging**
